### ISSUE TITLE
Issue when using yum

### ISSUE THREAD

**Issue by fredoche** [spartacus06/rpi2-fedora-image-builder#1]
Hi,

First of all, thank you for creating this builder.
I successfully used your work to boot my rpi. However, I can't install any software using yum.
The file /etc/yum.repo.d.fedora.repo has the baseurl field commented:

```
name=Fedora $releasever - $basearch
failovermethod=priority
#baseurl=http://download.fedoraproject.org/pub/fedora/linux/releases/$releasever/Everything/$basearch/os/
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch
enabled=1
metadata_expire=7d
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False
```

Is it expected or should am I doing something wrong?
Thanks for help

**Comment by sjenning** [comment]
Having baseurl commented is normal, as long as both baseurl and metalink aren't commented out at the same time.

Can you provide the output of the yum command when you try to run it?

**Comment by fredoche** [comment]
```
[fred@localhost ~]$ sudo yum update
[sudo] password for fred: 


 One of the configured repositories failed (Fedora 21 - armhfp),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable fedora

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=fedora.skip_if_unavailable=true

Cannot retrieve metalink for repository: fedora/21/armhfp. Please verify its path and try again
```

I can ping the metalink though:

```
[fred@localhost ~]$ ping mirrors.fedoraproject.org
PING wildcard.fedoraproject.org (209.132.181.16) 56(84) bytes of data.
64 bytes from wildcard.fedoraproject.org (209.132.181.16): icmp_seq=1 ttl=42 time=154 ms
```

**Comment by sjenning** [comment]
Weird.  My only thought is that the mirror you are being routed to through the metalink doesn't have the armhfp repo.  You might try commenting out the metalink line and directly supply a baserul:

```
baseurl=http://mirror.pnl.gov/fedora/linux/releases/21/Everything/armhfp/os/
```

**Comment by sjenning** [comment]
Also do a `yum clean all` for good measure

**Comment by fredoche** [comment]
Weird it keeps saying the same error... I'll restart from scratch tonight, from another network. Let me know if you have any other clue.
Thanks for your help

**Comment by fredoche** [comment]
Hi,

Found out that it is because my rpi's date was set at epoch (1 jan 1970) , and so failed the certificate check. Yum output was not explicit , contrary to the dnf's one which told me about the bad CA validation.
Once the date set, everything went smooth.
Btw , do you have a recommended method to sync time after install? Should one install a ntp daemon, or do you stick with a manual date setup ?

**Comment by fredoche** [comment]
I also added the line exclude=kernel\* into /etc/dnf.conf since the kernel is supposed to come from the rpi foundation at the moment.

**Comment by sjenning** [comment]
Ah, interesting.  Yes, ntpd.  And yes to excluding the kernel updates from Fedora.  Great tips, thanks.
