### ISSUE TITLE
Panic at boot

### ISSUE THREAD

**Issue by monnerat** [spartacus06/rpi2-fedora-image-builder#9]
Hi,
First, thanks for these scripts that run very well, as far as the image building is concerned.

However, whatever the F21 or F22 image I use, it always ends up with a panic at boot:

kernel panic, attempted to kill init exitcode=0x00000004

This comes just after recognition of the USB hub (sorry, no capture possible).
I tried without command line and with a cmdline.txt telling the rootfs, rootfstype, elevator=deadline, rootwait... without success.
The config.txt only sets config_hdmi_boost=5.

Did you experience the same problem and do you have any hints ?

Thanks in advance.

**Comment by sjenning** [comment]
I just did a build with the current tree and it works for me.  No settings.conf (defaults). My resources/config.txt is the one from sample-resources.

Do you have a 2GB+ card?  In F22 the rootfs no longer fits on a 1GB card.

**Comment by monnerat** [comment]
Thanks for your answer.

Yes, I have a 32Gb sd card.
settings.conf is:
<quote>
#IMAGEURL="http://mirror.pnl.gov/fedora/linux/releases/22/Images/armhfp/Fedora-Minimal-armhfp-22-3-sda.raw.xz"
IMAGEURL="file:///nobackup/raspberry/Fedora-Mate-armhfp-22-3-sda.raw.xz"
 # size in MB
BOOTSIZE=500
ROOTSIZE=4000
COMPRESS=1
</quote>
I updated the script to use curl instead of wget to support the file:// scheme.
The downloaded file checksum is correct.

There are no error listed while builing the image.
I then:
xzcat Fedora-Mate-armhfp-22-3-sda.raw.img.xz | dd of=/dev/sdd bs=4M
partprobe /dev/sdd
gparted            # to extend the /dev/sdd2 partition to the full sd size.
sync

**Comment by sjenning** [comment]
First, you don't have to make your curl changes.  Just keep the Fedora-Minimal-armhfp-22-3-sda.raw.xz in the root directory; the script looks for it there before trying to downloading.

I followed your procedure minus the compression and root filesystem expansion and it worked just fine.  I resized the root partition with fdisk, removing partition 2 then re-adding at the same offset with the new size.  Then resize2fs.  It still worked.

So, not sure what is going wrong.

**Comment by monnerat** [comment]
I found the problem:
They sold me a B+ for a PI 2 :-((
exitcode=0x00000004 is th signal number: SIGILL --> illegal instruction. init probably kills itself.
So if I don't get a true Pi2, i'll have to use Pidora or recompile everything :-))
Sorry for the noise, and many thanks for your support.
